// <auto-generated />
namespace ProviderCustomers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SetPlanRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetPlanRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201303092042525_SetPlanRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
