// <auto-generated />
namespace ProviderCustomers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLogoColumnToSite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLogoColumnToSite));
        
        string IMigrationMetadata.Id
        {
            get { return "201303100601402_AddLogoColumnToSite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
