// <auto-generated />
namespace ProviderCustomers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemoveRequiredConstraintFromHostingPlanOfSite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveRequiredConstraintFromHostingPlanOfSite));
        
        string IMigrationMetadata.Id
        {
            get { return "201303100448342_RemoveRequiredConstraintFromHostingPlanOfSite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
